#!/usr/bin/env python3
"""
Aggregate results/*.json (one file per platform, written by
run_benchmark.py) into a single markdown results matrix
(RESULTS.md) plus bar charts (results/charts/*.png).

    python -m src.harness.report

Re-run any time after adding/updating a platform's results file --
this never re-runs the benchmark itself, it only reads and formats.
"""
import glob
import json
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


def load_all(results_dir="results"):
    out = {}
    for path in sorted(glob.glob(os.path.join(results_dir, "*.json"))):
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        out[data["platform"]] = data
    return out


def fmt(v, digits=1):
    return f"{v:,.{digits}f}" if isinstance(v, (int, float)) else str(v)


def md_table(headers, rows):
    lines = ["| " + " | ".join(headers) + " |",
             "|" + "|".join(["---"] * len(headers)) + "|"]
    for row in rows:
        lines.append("| " + " | ".join(str(c) for c in row) + " |")
    return "\n".join(lines)


def build_markdown(all_results: dict) -> str:
    platforms = list(all_results.keys())
    out = ["# Results\n", "_Generated by `python -m src.harness.report`. Do not hand-edit — "
           "re-run the report after re-running any benchmark._\n"]

    # Specs
    rows = []
    for p in platforms:
        r = all_results[p]
        s = r["specs"]
        rows.append([r["display_name"], r.get("region", ""), s.get("tier_name", ""),
                     s.get("vcpu", ""), s.get("ram_gb", ""), s.get("disk_gb", "")])
    out.append("## Instance specs (fairness check)\n")
    out.append(md_table(["Platform", "Region", "Tier", "vCPU", "RAM (GB)", "Disk (GB)"], rows))
    out.append("")

    # Dataset
    any_manifest = next(iter(all_results.values()))["dataset_manifest"] if all_results else {}
    out.append("## Dataset\n")
    out.append(f"- Source: {any_manifest.get('source')}\n"
                f"- Nodes: {any_manifest.get('node_count'):,}\n"
                f"- Relationships: {any_manifest.get('relationship_count'):,}\n"
                f"- Sampling method: {any_manifest.get('sampling_method')}\n")

    # Loading
    rows = []
    for p in platforms:
        r = all_results[p]
        ld = r["loading"]
        rows.append([r["display_name"],
                     fmt(ld["nodes"]["throughput_per_s"], 0),
                     fmt(ld["relationships"]["throughput_per_s"], 0),
                     fmt(ld["total_wall_clock_s"], 1)])
    out.append("## Data loading\n")
    out.append(md_table(["Platform", "Nodes/s", "Relationships/s", "Total wall-clock (s)"], rows))
    out.append("")

    # Traversals
    out.append("## Traversal latency (ms)\n")
    rows = []
    for p in platforms:
        r = all_results[p]
        row = [r["display_name"]]
        for hop in ("1_hop", "2_hop", "3_hop"):
            st = r["traversals"][hop]["stats"]
            row += [fmt(st["p50_ms"], 2), fmt(st["p95_ms"], 2)]
        rows.append(row)
    out.append(md_table(
        ["Platform", "1-hop p50", "1-hop p95", "2-hop p50", "2-hop p95", "3-hop p50", "3-hop p95"],
        rows,
    ))
    out.append("")

    # Lookups
    out.append("## Lookup latency (ms)\n")
    rows = []
    for p in platforms:
        r = all_results[p]
        pt = r["lookups"]["point"]["stats"]
        ix = r["lookups"]["indexed"]["stats"]
        rows.append([r["display_name"], fmt(pt["p50_ms"], 2), fmt(pt["p95_ms"], 2),
                     fmt(ix["p50_ms"], 2), fmt(ix["p95_ms"], 2),
                     r["lookups"]["indexed"].get("indexed_property", "")])
    out.append(md_table(
        ["Platform", "Point p50", "Point p95", "Indexed p50", "Indexed p95", "Indexed on"],
        rows,
    ))
    out.append("")

    # Aggregation
    out.append("## Aggregation latency (ms)\n")
    rows = []
    for p in platforms:
        r = all_results[p]
        st = r["aggregation"]["stats"]
        rows.append([r["display_name"], fmt(st["p50_ms"], 2), fmt(st["p95_ms"], 2)])
    out.append(md_table(["Platform", "p50", "p95"], rows))
    out.append("")

    # Mixed workload
    out.append("## Mixed read/write throughput\n")
    rows = []
    for p in platforms:
        r = all_results[p]
        for m in r["mixed_workload"]:
            rows.append([r["display_name"], m["concurrency"], f"{int(m['write_ratio']*100)}%",
                         fmt(m["qps"], 1), fmt(m["latency_stats"]["p50_ms"], 2),
                         fmt(m["latency_stats"]["p95_ms"], 2), m["failed_ops"]])
    out.append(md_table(
        ["Platform", "Concurrency", "Write %", "QPS", "Latency p50", "Latency p95", "Failed ops"],
        rows,
    ))
    out.append("")

    # Footprint
    out.append("## Footprint\n")
    rows = []
    for p in platforms:
        r = all_results[p]
        fp = r["footprint"]
        rows.append([r["display_name"], fmt(fp.get("stored_bytes")) if fp.get("stored_bytes") else "n/a",
                     fp.get("note", "")])
    out.append(md_table(["Platform", "Stored bytes", "Note"], rows))
    out.append("")

    # Caveats
    out.append("## Caveats captured during these runs\n")
    any_caveats = False
    for p in platforms:
        for c in all_results[p].get("caveats", []):
            out.append(f"- **{all_results[p]['display_name']}**: {c}")
            any_caveats = True
    if not any_caveats:
        out.append("- None recorded automatically. Add manual caveats here (free-tier "
                    "throttling you observed, network variance, timeouts, etc.).")

    return "\n".join(out)


def build_charts(all_results: dict, out_dir="results/charts"):
    os.makedirs(out_dir, exist_ok=True)
    platforms = list(all_results.keys())
    names = [all_results[p]["display_name"] for p in platforms]

    # Traversal p95 by hop depth
    fig, ax = plt.subplots(figsize=(8, 5))
    width = 0.25
    import numpy as np
    x = np.arange(len(platforms))
    for i, hop in enumerate(("1_hop", "2_hop", "3_hop")):
        vals = [all_results[p]["traversals"][hop]["stats"]["p95_ms"] for p in platforms]
        ax.bar(x + i * width, vals, width, label=hop.replace("_", "-"))
    ax.set_xticks(x + width)
    ax.set_xticklabels(names, rotation=20, ha="right")
    ax.set_ylabel("p95 latency (ms)")
    ax.set_title("Traversal p95 latency by hop depth")
    ax.legend()
    fig.tight_layout()
    fig.savefig(os.path.join(out_dir, "traversal_p95.png"), dpi=150)
    plt.close(fig)

    # Mixed workload QPS vs concurrency
    fig, ax = plt.subplots(figsize=(8, 5))
    for p in platforms:
        r = all_results[p]
        cs = [m["concurrency"] for m in r["mixed_workload"]]
        qs = [m["qps"] for m in r["mixed_workload"]]
        if cs:
            ax.plot(cs, qs, marker="o", label=r["display_name"])
    ax.set_xlabel("Concurrent clients")
    ax.set_ylabel("Sustained QPS")
    ax.set_title("Mixed workload throughput vs. concurrency")
    ax.legend()
    fig.tight_layout()
    fig.savefig(os.path.join(out_dir, "mixed_qps_vs_concurrency.png"), dpi=150)
    plt.close(fig)

    # Ingest throughput
    fig, ax = plt.subplots(figsize=(8, 5))
    vals = [all_results[p]["loading"]["relationships"]["throughput_per_s"] for p in platforms]
    ax.bar(names, vals)
    ax.set_ylabel("Relationships/s")
    ax.set_title("Ingest throughput")
    plt.xticks(rotation=20, ha="right")
    fig.tight_layout()
    fig.savefig(os.path.join(out_dir, "ingest_throughput.png"), dpi=150)
    plt.close(fig)


def main():
    all_results = load_all()
    if not all_results:
        print("No results found in results/*.json yet -- run src/harness/run_benchmark.py "
              "for at least one platform first.")
        return
    md = build_markdown(all_results)
    with open("RESULTS.md", "w", encoding="utf-8") as f:
        f.write(md)
    print("Wrote RESULTS.md")
    try:
        build_charts(all_results)
        print("Wrote results/charts/*.png")
    except Exception as e:
        print(f"Chart generation skipped: {e}")


if __name__ == "__main__":
    main()
